### ISSUE TITLE
初始化失败

### ISSUE THREAD

**Issue by effectZz** [Yanyutin753/chatgpt-wechat-#10]
日志提示 Failed to init SINGSONG, diabled. 'fakeIP',请问应该怎么设置呢.

**Comment by Yanyutin753** [comment]
ip不对

**Comment by effectZz** [comment]
请问 两个参数是写什么，有没有例子呀。

**Comment by Yanyutin753** [comment]
![正在上传 296500295...]
不就一个嘛哈哈哈哈哈
填你vercel部署这个服务的url

**Comment by effectZz** [comment]
我是服务器docker部署的NeteaseCloudMusicApi ,然后  {"api_url": "ip:3000"} 这样配置的,一直提示服务器错误.

**Comment by effectZz** [comment]
请问 fakeIP必须设置不设置就会报错,但是fakeIP是做什么不太清楚

**Comment by Yanyutin753** [comment]
？？？这是啥项目 我咋不记得有这个fakeip

**Comment by Yanyutin753** [comment]
你的http
呢

**Comment by Yanyutin753** [comment]
完整的网址地址啊

**Comment by effectZz** [comment]
readme上的部署是#installp https://github.com/befantasy/singsong.git

**Comment by effectZz** [comment]
#installp https://github.com/Yanyutin753/chatgpt-wechat-singSong.git  
用这个地址  #scanp的时候 会报错
Failed to import plugin singSong: No module named 'plugins.singSong.songSing'

**Comment by Yanyutin753** [comment]
复制代码返回到plugin文件夹里面
