### ISSUE TITLE
无法登录

### ISSUE THREAD

**Issue by RMlalala** [Yanyutin753/chatgpt-wechat-#11]
大佬就是我按照链接扫码登录，登上去了，但机器人一直提示“😭请检查您是否登录账户”，这是怎么回事呢

**Comment by Yanyutin753** [comment]
你看看功能能不能用，应该没啥问题

**Comment by RMlalala** [comment]
功能没问题，就是vip音乐只有30s的时间

**Comment by Yanyutin753** [comment]
有会员吗 可以试试问问对应网易云api的作者

**Comment by RMlalala** [comment]
有会员的

**Comment by RMlalala** [comment]
好的，谢谢大佬

**Comment by zhaolu1206** [comment]
/login/status 显示 {"data":{"code":200,"account":null,"profile":null}}
是已登录状态吗？

**Comment by zhaolu1206** [comment]
登录状态是成功的，但是微信bot播放的vip歌曲还是30秒

**Comment by Yanyutin753** [comment]
我只调用的，具体你可以问问api的作者
