### ISSUE TITLE
singsong插件根据设置可以使用了，但每次播放音乐都是下载歌曲后才能播放，想问问怎样调用接口才会在线播放呢

### ISSUE THREAD

**Issue by leungyiuhoi** [Yanyutin753/chatgpt-wechat-#7]
singsong插件根据设置可以使用了，但每次播放音乐都是下载歌曲后才能播放，想问问怎样调用接口才会在线播放呢
![Uploading 925233f58bd1e8613d2c185834960dd.jpg…]()

**Comment by Yanyutin753** [comment]
在线播放的话，可能需要用链接，点击链接进行播放，可以参考我注解的代码，但是个人号，链接就不能超链接，可能会有些不美观
