### ISSUE TITLE
大佬能否给个api规范吗，我填写的ip+端口，不能被正常识别

### ISSUE THREAD

**Issue by helloyangy** [Yanyutin753/chatgpt-wechat-#8]

**Comment by Yanyutin753** [comment]
![image](https://github.com/Yanyutin753/chatgpt-wechat-singSong/assets/132346501/1c8b5f39-0798-41ef-a7e5-432ebf56ba4d)

ip+端口 能出现正常运行的图 就说明没问题，填到json文件里面就行了

**Comment by Yanyutin753** [comment]
接口文档你可以上图的查看文档，如果你ip+端口号能运行出这个界面，如果你是https那就直接填https://ip+端口，如果你是http的话就是http://ip+端口

**Comment by helloyangy** [comment]
好的，解决了，我重新登录机器人就可以正常识别api

**Comment by zhaolu1206** [comment]
我是用vercel部署的，我的apiurl应该怎么填？下面还有一个fakeip，这个应该怎么填？

**Comment by Yanyutin753** [comment]
填你的部署的服务domain网址

**Comment by zhaolu1206** [comment]
还有一个问题，有些音乐只能播放30秒，购买网易会员可以解决吗？

**Comment by Yanyutin753** [comment]
你得看你拉的vercel服务能不能行了
