### ISSUE TITLE
大佬能看看这是什么问题吗（错误的原因是连接被对等方重置，导致无法连接到代理。）

### ISSUE THREAD

**Issue by 17512074835** [Yanyutin753/chatgpt-wechat-#9]
requests.exceptions.ProxyError: HTTPSConnectionPool(host='netease-cloud-music-api-pi-six-91.vercel.app', port=443): Max retries exceeded with url: /search?keywords=%E6%B5%B7%E9%98%94%E5%A4%A9%E7%A9%BA/search&keywords=%E8%B0%81&limit=10 (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(104, 'Connection reset by peer')))

**Comment by Yanyutin753** [comment]
换个国内域名试试
